//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realMiniProjet.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_ArchivedReport
    {
        public int Id { get; set; }
        public int Id_student { get; set; }
        public int Id_archivedReport { get; set; }
    
        public virtual ArchivedReport ArchivedReport { get; set; }
        public virtual Student Student { get; set; }
    }
}
